GET https://backend-repository-t82r.onrender.com/hello
Content-Type: : application/json

####
POST https://backend-repository-t82r.onrender.com/api/groups
Content-Type: application/json

{
    "name": "test",
    "password":"abcde",
    "isPublic": false,
    "introduction": "해위",
    "likeCount": 4
}

